[project]
name = "easteregg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dataclass-wizard>=0.35.0",
    "playwright>=1.50.0",
    "pyright>=1.1.396",
    "ruff>=0.9.9",
]

[tool.ruff]
line-length = 100

[tool.ruff.format]
quote-style = "single"
