[project]
version = "1.0.0"
name = "easteregg"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "playwright>=1.50.0",
    "pyparsing>=3.2.3",
    "pyright>=1.1.396",
    "ruff>=0.9.9",
]
package-mode = false

[tool.ruff]
line-length = 100

[tool.ruff.format]
quote-style = "single"

[tool.poetry]
name = "easteregg"
version = "0.1.0"
authors = ["Bhargav Kulkarni <bhargavkishork@gmail.com>"]
description = "Add your description here"
