= EasterEgg
Bhargav Kulkarni

== Reading List

- https://cnandi.com/docs/icfp18-cr.pdf[ReIncarnate]: CAD semantics
- https://dl.acm.org/doi/abs/10.1145/3729278[CartoKit]: Similar IR to Skia. Worth reading!

== TODO

* [ ] Define easteregg in egglog.
** [ ] Might have to redefine this, now that we are formalizing the skia semantics.
* [x] Write a ``.skp`` compiler.
* [ ] Redo all the SkiaOpt work.
** [x] All the SkiaOpt unit tests pass.
** [ ] Maybe try using the SkiaOpt website skps too?
* [ ] Measure memory before and after optimization.
** Not on the critical path right now.
* [ ] Increase number of urls.
** [x] Add top 100 from Wikipedia.
** [ ] Add some fun website like, Zed, Minecraft etc..
* [ ] Add rewrite rules.
** [ ] Replicate SkiaOpt's rewrite rules.
*** May not be worth doing, given we have completely different egglog languages.
** [ ] Come up with new ones.
* [ ] Define Skia semantics.
** [x] Write a verifier for the Chrome subset of Skia.
** [ ] Define the Chrome subset of Skia.
** [ ] Define the denotational semantics of Skia.
* [ ] Write the paper.

== Semantics

xref:semantics.adoc[]

== Important Skia links

* https://github.com/google/skia/blob/main/tools/debugger/DrawCommand.cpp[DebugCanvas.h]
  has a bunch of ``toJSON`` methods that describe what Skia serializes to JSON.
  For some more complicated stuff like Shaders have ``flatten`` methods that are
  not here but in the files where they are defined.
** https://github.com/google/skia/blob/main/src/shaders/SkPictureShader.cpp[SkPictureShader],
   https://github.com/google/skia/blob/094ac350125ff98b8331697e469230ef1a92e251/src/core/SkPicture.cpp#L314[SkPicture],
   https://github.com/google/skia/blob/094ac350125ff98b8331697e469230ef1a92e251/src/core/SkPictureData.cpp#L281[SkPictureData]
   are important references for how ``SkPictureData`` are flattened.

== Things to think about

- Do other browsers use a different subset of Skia?
- Do filters affect performance? Is rearranging a filter worth it?
- Difference between clips and geometries.

== Compiling Paints

Very complicated shit. Will be important in formalizing the denotational
semantics of Skia. Paint is 2 things, how the shape is filled, and how the
boundaries are drawn. The shape can be filled in 2 ways.

* Just a straight up color
* Or a shader. This generates per pixel colors to fill. It replaces a solid
  color with complex patterns/gradients etc.

I still need to figure out how filters(both color and image) fit into all of
this.

== Interesting Benchmarks
=== Non-opaque SaveLayers

* bilibili layer 56
* duckduckgo 3
* duckduckgo 6
* ebay 0, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18
* fandom layer 2
* instagram layer 0

=== Tons of ImageFIlters

- github 10, 15, 16, 2, 7, 9
- globo 0, 30, 33
- google 1

=== DstIn masks

Stuff like this:
....
ᐊ SrcOver ClipRect [483.0 272.0 745.0 296.0], Mat [...]
  SaveLayer Color(255 0 0 0)
  Empty
  ᐊ SrcOver ClipRect [483.0 272.0 745.0 296.0], Mat [...]
    Rect [483.0 272.0 745.0 296.0] Color(255 0 0 0)
  ᐊ DstIn ClipRect [483.0 272.0 745.0 296.0], Mat [...]
    SaveLayer Color(255 0 0 0)
    Empty
    ᐊ SrcOver ClipRect [483.0 272.0 745.0 296.0], Mat [...]
      TextBlob 482.547 290.0 [-10.6328 -16.0938 262.934 5.19531] Color(255 0 0 0)
....

* Baidu layer 0
* Bilibli layer 5 (DstIn with shader), 47
* Canvas 0

=== Shaders within opaque SaveLayers

....
ᐊ SrcOver ClipRect [0.0 3239.0 1280.0 3599.0], Mat [...]
  SaveLayer Color(179 0 0 0)
  Empty
  ᐊ SrcOver ClipRect [0.0 3239.0 1280.0 3599.0], Mat [...]
    SaveLayer Color(255 0 0 0)
    Empty
    ᐊ Other ClipRect [0.0 3239.0 1280.0 3599.0], Mat [...]
      Rect [0.0 0.0 1833.0 1833.0] Shader
....

== Internals
=== Benchmarks

Benchmarks are generated by link:scripts/dl_skps.py[]. The list of benchmark
urls can be found in link:scripts/urls.toml[]. The benchmark script generates
benchmarks nested in folders, but the actual nightly pipeline expects flat
files, with the website name prefixed to `.skp` file. link:scripts/flatten.py[]
does just that. The actually binary `.skp` files of the entire benchmark suite
are huge(Gb huge). So *NEVER* commit them. Only ever commit the serialized json
file. The serialization is taken care by the `skp_parser` util in skia.

=== Compiling Skia

[source, bash]
--
cd skia
python3 tools/git-sync-deps
python3 bin/fetch-ninja
./bin/gn gen out/debug
ninja -C out/debug dm skp_parser
--

=== Compiling Egglog

For some reason this is exceedingly annoying. You have to fiddle with rust
versions. I have forgotten how to do this.

=== Pipeline

`.skp` file is first verified by link:verify.py[]. Then compiled to egglog by
link:skp2egg.py[]. Then link:egglog_runner.py[] runs the compilled egglog `.skp`
in egglog. link:printegg.py[] formats the unreadable and highly nested s-exp
format of egglog into something more readable. We run this script on the pre-
and post-optimized egglog ``.skp``s. We also run the pre- and post-optimized
``.skp`` through link:eegg2png.py[], which replays the commands with the
``skia-python`` library to build a png, which we use to check if our
optimizations produce the same image. All of these scripts are orchestrated by
link:make_report.py[] to create a nice formatted HTML table to view in your
browser.
