#+title:  EasterEgg
#+date:   [2025-11-03 Mon]
#+author: Bhargav Kulkarni

* Requirements

- ~uv~
- ~egglog~ (needs Rust)

* Reading List

- [[https://cnandi.com/docs/icfp18-cr.pdf][ReIncarnate]]: CAD semantics
- [[https://dl.acm.org/doi/abs/10.1145/3729278][CartoKit]]: Similar IR to Skia. Worth reading!

* Todo

- [X] Define easteregg in egglog.
  - [X] Might have to redefine this, now that we are formalizing the skia semantics.
- [X] Write a ~.skp~ compiler.
- [-] Redo all the SkiaOpt work.
  - [X] All the SkiaOpt unit tests pass.
  - [ ] Maybe try using the SkiaOpt website skps too?
- [ ] Measure memory before and after optimization.
  - Not on the critical path right now.
- [-] Increase number of urls.
  - [X] Add top 100 from Wikipedia.
  - [ ] Add some fun website like, Zed, Minecraft etc..
- [X] Add rewrite rules.
  - [X] Replicate SkiaOpt's rewrite rules.
    - May not be worth doing, given we have completely different egglog languages.
  - [X] Come up with new ones.
- [X] Define Skia semantics.
- [X] Define the Chrome subset of Skia.
- [X] Write a verifier for the Chrome subset of Skia.
- [ ] Try to get rid of most of the ~SaveLayers~ within the benchmark suite
- [ ] Implement the actual optimizer withing Skia.
- [ ] Write the paper.

* Semantics

See the [[https://github.com/bhargavkulk/lambda_skia][lambda_skia repo]].

* Important Skia links

- [[https://github.com/google/skia/blob/main/tools/debugger/DrawCommand.cpp][DrawCommand.cpp]] has a bunch of ``toJSON`` methods that describe what Skia
  serializes to JSON. For some more complicated stuff like Shaders have
  ``flatten`` methods that are not here but in the files where they are defined.
- [[https://github.com/google/skia/blob/main/src/shaders/SkPictureShader.cpp][SkPictureShader]], [[https://github.com/google/skia/blob/094ac350125ff98b8331697e469230ef1a92e251/src/core/SkPicture.cpp#L314][SkPicture]], [[https://github.com/google/skia/blob/094ac350125ff98b8331697e469230ef1a92e251/src/core/SkPictureData.cpp#L281][SkPictureData]] are important references for how
  ``SkPictureData`` are flattened.

* Things to think about

- Do other browsers use a different subset of Skia?
- Do filters affect performance? Is rearranging a filter worth it?
- Difference between clips and geometries.

* Compiling Paints

Very complicated shit. Will be important in formalizing the denotational
semantics of Skia. Paint is 2 things, how the shape is filled, and how the
boundaries are drawn. The shape can be filled in 2 ways.

- Just a straight up color
- Or a shader. This generates per pixel colors to fill. It replaces a solid
  color with complex patterns/gradients etc.

I still need to figure out how filters(both color and image) fit into all of
this.

* Interesting Benchmarks
** Non-opaque SaveLayers

- bilibili layer 56
- duckduckgo 3
- duckduckgo 6
- ebay 0, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18
- fandom layer 2
- instagram layer 0

** Tons of ImageFIlters

- github 10, 15, 16, 2, 7, 9
- globo 0, 30, 33
- google 1

** DstIn masks

Stuff like this:

#+begin_example
ᐊ SrcOver ClipRect [483.0 272.0 745.0 296.0], Mat [...]
  SaveLayer Color(255 0 0 0)
  Empty
  ᐊ SrcOver ClipRect [483.0 272.0 745.0 296.0], Mat [...]
    Rect [483.0 272.0 745.0 296.0] Color(255 0 0 0)
  ᐊ DstIn ClipRect [483.0 272.0 745.0 296.0], Mat [...]
    SaveLayer Color(255 0 0 0)
    Empty
    ᐊ SrcOver ClipRect [483.0 272.0 745.0 296.0], Mat [...]
      TextBlob 482.547 290.0 [-10.6328 -16.0938 262.934 5.19531] Color(255 0 0 0)
#+end_example

- Baidu layer 0
- Bilibli layer 5 (DstIn with shader), 47
- Canvas 0

* Shaders within opaque SaveLayers

#+begin_example
ᐊ SrcOver ClipRect [0.0 3239.0 1280.0 3599.0], Mat [...]
  SaveLayer Color(179 0 0 0)
  Empty
  ᐊ SrcOver ClipRect [0.0 3239.0 1280.0 3599.0], Mat [...]
    SaveLayer Color(255 0 0 0)
    Empty
    ᐊ Other ClipRect [0.0 3239.0 1280.0 3599.0], Mat [...]
      Rect [0.0 0.0 1833.0 1833.0] Shader
#+end_example

* Internals
** Benchmarks

Benchmarks are generated by [[file:utils/dl_skps.py][scripts/dl_skps.py]]. The list of benchmark urls can
be found in [[file:utils/urls.toml][utils/urls.toml]]. The benchmark script generates benchmarks nested in
folders, but the actual nightly pipeline expects flat files, with the website
name prefixed to =.skp= file. [[file:utils/flatten.py][utils/flatten.py]] does just that. The actually
binary =.skp= files of the entire benchmark suite are huge(Gb huge). So *NEVER*
commit them. Only ever commit the serialized json file. The serialization is
taken care by the ~skp_parser~ util in skia.

** Compiling Skia

#+begin_src bash
cd skia
python3 tools/git-sync-deps
python3 bin/fetch-ninja
./bin/gn gen out/debug
ninja -C out/debug dm skp_parser
#+end_src

** Compiling Egglog

For some reason this is exceedingly annoying. You have to fiddle with rust
versions. ~rustup~ usually fixes this. See [[file:nightly.sh][nightly.sh]].

** Pipeline

~.skp~ file is first verified by [[file:src/verify.py][verify.py]]. Then compiled to egglog by
[[file:src/skp_compiler.py][skp_compiler.py]]. Then [[file:src/egglog_runner.py][egglog_runner.py]] runs the compilled egglog skp in egglog.
We run this script on the pre- and post-optimized egglog skps. We also run the
pre- and post-optimized skp through [[file:src/renderer.py][renderer.py]], which replays the commands with
the ~skia-python~ library to build a png, which we use to check if our
optimizations produce the same image. All of these scripts are orchestrated by
[[file:src/mk_report.py][mk_report.py]] to create a nice formatted HTML table to view in your browser.

* Some links

https://bugs.chromium.org/p/skia/issues/detail?id=2180
https://bugs.chromium.org/p/skia/issues/detail?id=5716
These two are bugs in Skia related to their existing optimizer
He also sent a huge number related to the Chrome-side optimizer:
https://bugs.chromium.org/p/chromium/issues/detail?id=1006140
https://bugs.chromium.org/p/chromium/issues/detail?id=748485
https://bugs.chromium.org/p/chromium/issues/detail?id=749422
https://chromium-review.googlesource.com/c/chromium/src/+/589815
https://bugs.chromium.org/p/chromium/issues/detail?id=769603
https://bugs.chromium.org/p/chromium/issues/detail?id=1195276
https://chromium-review.googlesource.com/c/chromium/src/+/2851121
https://bugs.chromium.org/p/chromium/issues/detail?id=1302290
https://chromium-review.googlesource.com/c/chromium/src/+/3504971
