#+title: SkiaChrome
#+author: Bhargav Kulkarni

This document describes the subset of the Skia API generated by Google Chrome.

#+begin_example
SkiaChrome ::= DrawCommand
             | ClipCommand
             | Save
             | SaveLayer(Bounds, SaveLayerPaint)
             | Restore
#+end_example

* DrawCommand

#+begin_example
DrawCommand ::= drawRect(Rect, Paint)
              | drawRRect(RRect, Paint)
              | drawPath(Path, Paint)
              | drawPaint(Paint)
              | drawTextBlob(TextBlob, x, y, Paint)
              | drawImageRect(Image, Center: Rect, Dst: Rect, Filter, Paint)
#+end_example

** [[https://api.skia.org/classSkCanvas.html#a15a77a3479b8f8731442d4a4ea2772b3][drawRect]]

Draws SkRect rect using clip, SkMatrix, and SkPaint paint.

In paint: SkPaint::Style determines if rectangle is stroked or filled; if
stroked, SkPaint stroke width describes the line thickness, and SkPaint::Join
draws the corners rounded or square.

** [[https://api.skia.org/classSkCanvas.html#ab50290cf9da84da457652d73ea09c0f5][drawRRect]]

Draws SkRRect rrect using clip, SkMatrix, and SkPaint paint.

In paint: SkPaint::Style determines if rrect is stroked or filled; if stroked,
SkPaint stroke width describes the line thickness.

rrect may represent a rectangle, circle, oval, uniformly rounded rectangle, or
may have any combination of positive non-square radii for the four corners.

*** In Practice

But rrect usually compiles into radii for the 4 corners.

** [[https://api.skia.org/classSkCanvas.html#acddf41dddcd12333b061ce9c963616bb][drawPath]]

Draws SkPath path using clip, SkMatrix, and SkPaint paint.

SkPath contains an array of path contour, each of which may be open or closed.

In paint: SkPaint::Style determines if SkRRect is stroked or filled: if filled,
SkPath::FillType determines whether path contour describes inside or outside of
fill; if stroked, SkPaint stroke width describes the line thickness,
SkPaint::Cap describes line ends, and SkPaint::Join describes how corners are
drawn.

** [[https://api.skia.org/classSkCanvas.html#a64cf967c90d18c096b91519b0d5336a3][drawPaint]]

Fills clip with SkPaint paint.

SkPaint components, SkShader, SkColorFilter, SkImageFilter, and SkBlendMode
affect drawing; SkMaskFilter and SkPathEffect in paint are ignored.

** [[][drawTextBlob]]
