GitHub = 'https://github.com/'
Amazon = 'https://amazon.com/'
Ebay = 'https://ebay.com/'
Baidu = 'baidu.com'
Bilibili = 'bilibili.com'
Microsoft_Bing = 'bing.com'
Canva = 'canva.com'
ChatGPT = 'chatgpt.com'
DeepSeek = 'deepseek.com'
DuckDuckGo = 'duckduckgo.com'
Zen_News = 'dzen.ru'
Facebook = 'facebook.com'
Fandom = 'fandom.com'
Globo = 'globo.com'
Google_Search = 'google.com'
Instagram = 'instagram.com'
LinkedIn = 'linkedin.com'
Live = 'live.com'
Mail_ru = 'mail.ru'
Microsoft = 'microsoft.com'
Naver = 'naver.com'
Netflix = 'netflix.com'
Yahoo_News_Japan = 'news.yahoo.co.jp'
The_New_York_Times = 'nytimes.com'
Microsoft_365 = 'office.com'
Pinterest = 'pinterest.com'
Quora = 'quora.com'
Reddit = 'reddit.com'
Samsung = 'samsung.com'
SharePoint = 'sharepoint.com'
Telegram = 't.me'
Temu = 'temu.com'
TikTok = 'tiktok.com'
Twitch = 'twitch.tv'
VK = 'vk.com'
WhatsApp = 'whatsapp.com'
Wikipedia = 'wikipedia.org'
X = 'x.com'
Yahoo_JP = 'yahoo.co.jp'
Yahoo = 'yahoo.com'
Yandex = 'yandex.ru'
YouTube = 'youtube.com'
Zoom = 'zoom.us'
