= Skia Chrome API
Bhargav Kulkarni

This document describes the subset of the skia API used by Chrome. This subset
was collected over the 100 most commonly visited websites. This document is a
dual of the xref:semantics.adoc[Semantics] document in this same folder.

== State

While not visible in the ``.skp``, all drawing commands are run on a
https://api.skia.org/classSkCanvas.html[canvas]. Which is managed by a
https://api.skia.org/classSkSurface.html[canvas]. The canvas maintains the
state:

* The clip, which describes the drawing bounds.
* The transform, which describes the transform matrix for any subsequent
  drawings.

== Commands

Each command is a method belonging to the canvas.

=== Draw Commands
==== DrawPaint

https://api.skia.org/classSkCanvas.html#a64cf967c90d18c096b91519b0d5336a3

[source]
----
drawPaint(canvas, paint: Paint)
----

==== DrawRect

https://api.skia.org/classSkCanvas.html#a15a77a3479b8f8731442d4a4ea2772b3

[source]
----
drawRect(canvas, rect: Rect, paint: Paint)
----

==== DrawRRect

Draws a rounded rectangle.

https://api.skia.org/classSkCanvas.html#ab50290cf9da84da457652d73ea09c0f5

[source]
----
drawRRect(canvas, rrect: RRect, paint: Paint)
----

==== DrawPath

Draws a path.

https://api.skia.org/classSkCanvas.html#acddf41dddcd12333b061ce9c963616bb

[source]
----
drawPath(canvas, path: Path, paint: Paint)
----

==== DrawTextBlob

https://api.skia.org/classSkCanvas.html#aefcef6a4389f0ec225b2cf229a372826

Draws some text.

[source]
----
drawTextBlob(canvas, x, y, text, paint: Paint)
----

==== DrawImageRect

Draws an Image. Specifies how it gets mapped and cropped. There are also some sampling options.

https://api.skia.org/classSkCanvas.html#a2b0f0b16e87bdc2ec0ec595f3a80712c

Sampling: https://api.skia.org/structSkSamplingOptions.html

[source]
----
drawImageRect(canvas, image, src: Coords, dst: Coords, sampling, paint: Paint)
----

==== DrawDRRect

Draws the space between the inner and outer rounded rectangle.

https://api.skia.org/classSkCanvas.html#ad7149e359d4d0cfd2ad708e905f0d8c6

[source]
----
drawDRRect(canvas, outer: RRect, inner: RRect, paint: Paint)
----

==== DrawPoints

Draws points. THe resulting shape depends on the PointMode, which is either:

* Point: just draws the points
* Line: draws lines segments, connecting each point
* Polygon: closes the line segments

https://api.skia.org/classskcanvas.html#a1e9be2866798af6038ee3e724722d1f9

[source]
----
drawpoints(canvas, mode, points: point[], paint: paint)
----

==== DrawOval

Draws an Oval. Seems to be a specialized version of DrawRRect.

https://api.skia.org/classSkCanvas.html#a183daa228e12207a75660fae3dc5e3f9

[source]
----
drawOval(canvas, oval: Rect, paint: Paint)
----

=== State Commands

These commands manipulate the state of the canvas.

==== Save

Saves the current clip and transform onto the layer stack. This is restored back
when a matching <<Restore>> is called.

https://api.skia.org/classSkCanvas.html#ac98147dc771b47c7353a51e7c171e428

[source]
----
Save(canvas)
----

==== SaveLayer

Saves the current clip and transform onto the layer stack. Creates a new backing
surface. All subsequent commands until a matching <<Restore>> are directed to
the canvas of this surface. If a <<Paint,paint>> exists, then the paint is applied to the
surface before merging with the layer underneath. The attributes of the paint
applied to the surface are the <<Color,alpha>>, the <<Color_Filter,color
filter>>, the <<Image_Filter,image filter>> and the <<Blend_Mode,blend mode>>.
If a paint does not exist, assume a paint with only 100% opacity and ``SrcOver``
blend mode is used. The saveLayer also takes an optional bounds, but it seems
like it does nothing.

https://api.skia.org/classSkCanvas.html#a41aa2893a587e4a371342d7ff809b0d5

==== Restore

Restores state for <<Save>> and <<SaveLayer>>. Additionally blends new layer
created by SaveLayer onto the previous layer.

[source]
----
saveLayer(canvas, bounds: Optional[Rect], paint: Optional[Paint])
----

==== Concat44

Multiplies the input matrix with the current transform. All the various
transform operations like ``skew`` get compiled to this.

https://api.skia.org/classSkCanvas.html#adb493a60db8ccd84abbaa26fb9506bcf

[source]
----
concat(canvas, matrix: float[4][4])
----

==== ClipRect

Changes the current clip. How the clip changes is governed by the clip op, which
can either be intersection or difference.

https://api.skia.org/classSkCanvas.html#a193511e463259ceacfe0e4cf1be1393f

[source]
----
clipRect(canvas, rect: Rect, op: ClipOp[Int|Diff], doAntiAlias: bool)
----

==== ClipRRect

https://api.skia.org/classSkCanvas.html#afcefd4d2ac745ad086fd62f30bbd8564

[source]
----
clipRect(canvas, rrect: RRect, op: ClipOp[Int|Diff], doAntiAlias: bool)
----

==== ClipPath

https://api.skia.org/classSkCanvas.html#abc79bd478516f398c31ae9f501154184

[source]
----
clipPath(canvas, path: Path, op: ClipOp[Int|Diff], doAntiAlias: bool)
----

=== Shapes
==== Rectangles

Defined by left, top, right, bottom.

https://api.skia.org/structSkRect.html

==== Rounded Rectangles

Rect with 4 radii.

https://api.skia.org/classSkRRect.html

==== Path

Object representing path. The ``fillType`` governs what is filled, if the path
is closed. The path is constructed by stringing verbs between points. The verbs
used are:

* move
* cubic
* line
* conic
* quad
* close

https://api.skia.org/classSkPath.html

=== Paint

Paint controls how stuff is drawn. It is roughly made of 3 components:

* Fill: defines what is drawn in the shape.
* Stroke: defines how the boundaries of the shape are drawn.
* Transform: changes how what is drawn is drawn.

==== Fill
===== Color

Sets alpha and RGB used when stroking and filling. Skia orders colors as alpha,
red, blue, green.

https://api.skia.org/classSkPaint.html#a2afde76523eb9fafe22fca89b841e14b

[source]
----
paint.setColor(color: [A, R, G, B])
----

===== Dither

Distribute colors to emulate other colors if devide does not support .

===== Shader

While color sets a flat color throughout the shape, shaders allow for far more
control. See <<shader_desc,Shader>> for more details. Color is only used if this
is nullptr.

https://api.skia.org/classSkPaint.html#ab1fecafb4783c85159f701d195221354

==== Stroke

Stroke only works when the fill style is stroke or stroke and fill. It has the
following components

* stroke width
* stroke miter
* stroke join
* stroke cap
* dashing

=== Transform
==== Color Filter
==== Image Filter
==== Blend Mode
