name: Pyrefly Type Check
on:
 pull_request:
   branches: [main]
 workflow_dispatch:  # Allows manual triggering from the GitHub UI
jobs:
 typecheck:
   runs-on: ubuntu-latest
   steps:
     - name: Check out code
       uses: actions/checkout@v4

     - name: Install uv
       uses: astral-sh/setup-uv@v3

     - name: Set up Python
       run: uv python install

     - name: Install dependencies
       run: uv sync

     - name: Run Pyrefly Type Checker
       run: uv run pyrefly check
